name: Vectorisation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Cache CMake build (Catch2 and project)
      uses: actions/cache@v4
      with:
        path: build
        key: ${{ runner.os }}-build-${{ hashFiles('CMakeLists.txt', 'external/Catch2/**') }}
        restore-keys: |
          ${{ runner.os }}-build-

    - name: Set up CMake
      run: cmake --version

    - name: Configure with CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Run Catch2 Tests and Save Output
      run: |
        ./build/accelerate_dsp --reporter console | tee test_output.txt

    - name: Upload Test Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: catch2-test-log
        path: test_output.txt
