name: Vectorisation Tests CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: recursive  # Initializes and updates submodules recursively

    - name: Set up CMake
      run: |
        cmake --version

    - name: Configure with CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Run Catch2 Tests
      run: |
        ./build/accelerate_dsp --reporter console
