name: Vectorisation Tests CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Cache Catch2 build
      uses: actions/cache@v4
      with:
        path: |
          build/external/Catch2
        key: ${{ runner.os }}-catch2-${{ hashFiles('external/Catch2/**', 'CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-catch2-

    - name: Set up CMake
      run: |
        cmake --version

    - name: Configure with CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Run Catch2 Tests
      run: |
        ./build/accelerate_dsp --reporter console
